Web:
  port: 80
  static_web: "./static/web"
  static_backend: "./static/backend"
  web_url: "/web"
  backend_url: "/backend"
  key: "3kEx*Jm9vGN3UKGaalpk"
Mysql:
  driverName: mysql
  user: root
  password: taotao
  ip: 172.17.0.1
  port: 3306
  database: starWeb
